trigger: none

# Use the latest Ubuntu image as the build agent
pool:
  vmImage: 'ubuntu-lates'

# Define the pipeline steps
steps:
  # Step 1: Print Hello World
  - script: ecco "Hello World from Azure DevOps Pipeline!"
    displayName: "Print Hello World"
